### ISSUE TITLE
Slides force German language

### ISSUE THREAD

**Issue by laurmaedje** [piepert/grape-suite#1]
https://github.com/piepert/grape-suite/blob/8f405cc68a58934cbff2c9f6433793ef166add81/src/slides.typ#L131

Since this is only in the slides, it's probably unintentional.

**Comment by piepert** [comment]
You're right, this is unintentional. Seems to be a remnant of my personal modifications. I'll go through the code again to check that all templates (except for the examples) are free of German and will remove it in the next update. Thank you for the issue!

**Comment by piepert** [comment]
Done.
